### ISSUE TITLE
Code Splitting and server side Isomorphic React Apps

### ISSUE THREAD

**Issue by ansarizafar** [vesparny/react-kickstart#10]
Thanks for this amazing starter kit. Could you please guide me How to use code splitting and Server side rendering with the starter kit. I am also getting this error when using npm run eslint

'children' is missing in props validation for App  react/prop-types

**Comment by vesparny** [comment]
The starter kit is not mean to achieve ssr. Anyway you can easily implement it.
take a look here https://github.com/erikras/react-redux-universal-hot-example
