### ISSUE TITLE
Ability to run unit tests located in 'src'

### ISSUE THREAD

**Issue by ngduc** [vesparny/react-kickstart#12]
Hi vesparny, thanks for this great project.
I'm planning to create a PR to use 'mocha' command line instead of babel-node & run unit tests located in 'src' (find them recursively). I'd like to have component & its unit tests come together in a same directory.
This requires mocha & chai, sinon, etc.
What do you think? Thanks.

**Comment by vesparny** [comment]
hey,

I think load bring mocha as a dependency is an overkill for this purpose.
You can easily achieve what you need using glob and require every file from here https://github.com/vesparny/react-kickstart/blob/master/test/index.js#L17

Actually it would be a good idea to do so, I'll do it tonight and ping you back

**Comment by ngduc** [comment]
awesome! thanks.

**Comment by vesparny** [comment]
take a look at what I did, you just need to add every src folder to the glob pattern

**Comment by ngduc** [comment]
got it. any plan to bring in mocha, chai, sinon instead of tape?

**Comment by vesparny** [comment]
nope, actually I just moved from mocha to tape.

here is why:
https://medium.com/javascript-scene/why-i-use-tape-instead-of-mocha-so-should-you-6aa105d8eaf4#.idr9l7pmk
