### ISSUE TITLE
:wave: Hey! How do I get Browser History Working With Hot-dev-middleware

### ISSUE THREAD

**Issue by ppiekarczyk** [vesparny/react-kickstart#16]
Hey!

Your starter kit rocks!

I was wondering if you could help me get browser history working in development mode. Here are the docs from react-router's website:

https://github.com/rackt/react-router/blob/latest/docs/guides/basics/Histories.md#createbrowserhistory

Now, this is very similar to what you're using. My only issue is that I don't know how to care of this step:

```js
app.get('*', function (request, response){
  response.sendFile(path.resolve(__dirname, 'public', 'index.html'))
})
```

Mainly because I'm not sure where `index.html` lives!

Thanks again,
Peter

**Comment by vesparny** [comment]
Hey,

I don't understand what you mean by

>
Mainly because I'm not sure where index.html lives!

In order to have client-side routing you have to ensure that your server is always sending back the same page. So you have to create a catch-all route.

```js
app.get('*', function (request, response){
  response.sendFile(path.resolve(__dirname, 'public', 'index.html'))
})
```

**Comment by ppiekarczyk** [comment]
Thanks for getting back to me!

I tried that, but unfortunately I get this every time I try:

```
Error: ENOENT: no such file or directory, stat '/Users/peter/Sites/app/public/index.html'
   at Error (native)
````

**Comment by vesparny** [comment]
could you post your `devServer.js`?

**Comment by vesparny** [comment]
Normally if you use something like

```js
app.get('*', function (request, response){
  response.sendFile(path.resolve(__dirname, 'public', 'index.html'))
})
```
you will have a path corresponding to

`/The/folder/that/contains/the/file/public/index.html`

What is the absolute path of your `index.html` file?

**Comment by ppiekarczyk** [comment]
Hey,

my `devServer` file is mostly the same as your starter kit. I was also trying to get the proxy working but I haven't had any luck yet.

Is there supposed to be a `public` folder created? I have the `index.html` that lives in `src`, and an `index.html` that lives in `dist` but only after I build the project. I was hoping I could get this working for development if possible!

Thanks again!

```es6
var express = require('express')
var webpack = require('webpack')
var config = require('./webpack.config.dev')
var httpProxy = require('http-proxy')
var path = require('path')

var proxy = httpProxy.createProxyServer({})
var app = express()

var compiler = webpack(config)

app.use(require('webpack-dev-middleware')(compiler, {
  publicPath: config.output.publicPath,
  contentBase: 'src',
  stats: {
    colors: true,
    hash: false,
    timings: true,
    chunks: false,
    chunkModules: false,
    modules: false
  }
}))

app.use(require('webpack-hot-middleware')(compiler))

app.use(express.static(__dirname + '/dist'))

app.get('*', function (req, res){
  console.log('hi', req.url)
  res.sendFile(path.join(__dirname, 'dist', 'index.html'))
})

app.all('/api/v1/*', function (req, res) {
  console.log('requesting api....', req.url)
  proxy.web(req, res, {
    target: 'http://127.0.0.1:8081'
  })
})

proxy.on('error', function(e) {
  console.log('Could not connect to proxy, please try again...', e);
});

app.listen(config._hotPort, 'localhost', function (err) {
  if (err) {
    console.log(err)
  }
  console.info('==> 🌎 Listening on port %s. Open up http://localhost:%s/ in your browser.', config._hotPort, config._hotPort)
})

```

**Comment by vesparny** [comment]
For development just drop the catch all route.
The html file is generated by webpack.

**Comment by ppiekarczyk** [comment]
Thank you for the quick reply!

I dropped the catchall route (`*`) with browser history but unfortunately when I hit `/login` it says CANNOT GET `/login/`

**Comment by ppiekarczyk** [comment]
Does browser history in development work for you?

**Comment by vesparny** [comment]
I don't understand.

does the file '/Users/peter/Sites/app/public/index.html' exists?

can you give me the absolute path of the file?

**Comment by ppiekarczyk** [comment]
Nope! It doesn't exist 

Sent from Outlook Mobile




On Fri, Feb 5, 2016 at 7:24 AM -0800, "Alessandro Arnodo" <notifications@github.com> wrote:












I don't understand.



does the file '/Users/peter/Sites/app/public/index.html' exists?



can you give me the absolute path of the file?

**Comment by ppiekarczyk** [comment]
I've been looking through webpack-dev-middleware for some clues on how this is all supposed to work. Does this middleware create the public/index.html file for me when I'm running it?

Sent from Outlook Mobile




On Fri, Feb 5, 2016 at 7:24 AM -0800, "Alessandro Arnodo" <notifications@github.com> wrote:












I don't understand.



does the file '/Users/peter/Sites/app/public/index.html' exists?



can you give me the absolute path of the file?

**Comment by vesparny** [comment]
try to put back the catchall

```es6
const goodPath = '/Your/path/index.html'
app.get('*', function (req, res){
  console.log('test', req.url)
  res.sendFile(goodPath)
})
```

**Comment by ppiekarczyk** [comment]
Hey, 

No luck :*( 

Do you have browser history working with your setup?

I'm having this issue even when I clone a new project and replace `hashHistory` with `browserHistory`

Thanks again for your help! I appreciate it!

**Comment by vesparny** [comment]
There is definitely an issue,
I will look into it asap

**Comment by vesparny** [comment]
Try to replace the content of devServer.js with 

```es6
var path = require('path');
var express = require('express');
var webpack = require('webpack');
var config = require('./webpack.config.dev');

var app = express();

var compiler = webpack(config);
const middleware = require('webpack-dev-middleware')(compiler, {
  publicPath: config.output.publicPath,
  contentBase: 'src',
  stats: {
    colors: true,
    hash: false,
    timings: true,
    chunks: false,
    chunkModules: false,
    modules: false
  }
})

app.use(middleware);

app.use(require('webpack-hot-middleware')(compiler));

app.get('*', (req, res) => res.end(middleware.fileSystem.readFileSync(path.join(config.output.path, 'index.html'))))

app.use(express.static(__dirname + '/dist'));

app.listen(config._hotPort, 'localhost', function(err) {
  if (err) {
    console.log(err);
  }
  console.info("==> 🌎 Listening on port %s. Open up http://localhost:%s/ in your browser.", config._hotPort, config._hotPort);
});
```

**Comment by vesparny** [comment]
please note this is just a temporary solution.
I will provide a real fix in next release.

**Comment by ppiekarczyk** [comment]
I truly appreciate you just helping me out! Thank you for doing this!

I have an open weekend, if there's anything I can do to help you please let me know!

Thanks again!

**Comment by vesparny** [comment]
Please update to v3.3.0
Your issue should be fixed.

Thanks for pointing this out

**Comment by ppiekarczyk** [comment]
Thank you again!

**Comment by vesparny** [comment]
does it work now for you?

**Comment by ppiekarczyk** [comment]
Yes! Everything is fine, thanks!
