### ISSUE TITLE
code coverage doesn't seem to work properly

### ISSUE THREAD

**Issue by vesparny** [vesparny/react-kickstart#2]

**Comment by zanjs** [comment]
$ npm start

> react-kickstart@2.0.2 start E:\zan\www\webpack\react-kickstart
> node devServer

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:8000
    at Object.exports._errnoException (util.js:837:11)
    at exports._exceptionWithHostPort (util.js:860:20)
    at Server._listen2 (net.js:1231:14)
    at listen (net.js:1267:10)
    at net.js:1376:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:62:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:81:10)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\nodejs\\node.exe" "D:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE
npm ERR! react-kickstart@2.0.2 start: `node devServer`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-kickstart@2.0.2 start script 'node devServer'.
npm ERR! This is most likely a problem with the react-kickstart package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node devServer
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-kickstart
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\zan\www\webpack\react-kickstart\npm-debug.log

**Comment by vesparny** [comment]
You have some other process running on port 8000.
Anyways this is unrelated to this issue.

**Comment by zanjs** [comment]
$ npm start

> react-kickstart@2.0.2 start E:\zan\www\webpack\react-kickstart
> node devServer

==> 🌎 Listening on port 8000. Open up http://localhost:8000/ in your browser.
webpack built 810ade9ac7ff9eecb6eb in 204ms
Version: webpack 1.12.2
Time: 204ms
  Asset     Size  Chunks       Chunk Names
main.js  29.8 kB       0       main

ERROR in Cannot find module '../internal/baseIndexOf'
 @ multi main
webpack: bundle is now VALID.

**Comment by zanjs** [comment]
thank you

**Comment by zanjs** [comment]
ERROR in Cannot find module '../internal/baseIndexOf'

**Comment by vesparny** [comment]
How do you see this related to this issue?
