### ISSUE TITLE
Node scripts on Windows

### ISSUE THREAD

**Issue by jenswachtel** [vesparny/react-kickstart#9]
Hey,

not sure where to put this addition, but there's some issue with running the scripts (e.g. npm run build) with windows.

package.json adjustments for Windows
```
    "start": "node devServer.js",
    "build:start": "set NODE_ENV=production && node prodServer.js",
    "build": "rimraf dist && set NODE_ENV=production && webpack --config ./webpack.config.prod.js --progress --profile --colors",
```

Also, webpack and rimraf has to be installed globally. (npm install -g rimraf webpack)

**Comment by vesparny** [comment]
Hey, did you find a solution?
I cannot test on win
